// Auto-generated by scripts/gen-warrior-placeholders.js — do not edit manually.
// Re-run "npm run gen:placeholders" after importing new sprites in Cocos Creator.
export const WARRIOR_UUID_MAP: Record<string, string> = {
    '9bd0d349-03ca-4265-9d02-6207de479311': 'frog_2x2',
    '136c741e-af97-46bd-99cc-1ef517cecf8d': 'cat_2x2',
    'b7700eb1-321c-4d53-8154-6f8c363512a9': 'chicken_2x2',
    '3e2737f4-cfd0-4b19-a10a-903b03a95c0d': 'wolf_2x3',
    'd711232e-0b76-4af4-806b-4ad96802b3c6': 'eagle_2x3',
    'ad5ff102-0a2d-4cb2-8f05-3db6df74894d': 'lion_2x3',
    '3edf522c-f70a-4c69-a6ac-8e5ea06a38ab': 'dragon_2x4',
};
